apiVersion: v1
kind: Service
metadata:
  name: faq-accordion-main
  namespace: default
spec:
  selector:
    app: faq-accordion-main-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
